;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16

[/Script/GameplayTags.GameplayTagsList]
+GameplayTagList=(Tag="GameplayCue.Ability.Trail.Magic",DevComment="Ability Niagara VFX")
+GameplayTagList=(Tag="GameplayCue.Ability.Burst.Magic",DevComment="Ability Niagara VFX")
+GameplayTagList=(Tag="GPTags.VFX.AbilityTrail.Magic",DevComment="Ability Niagara VFX")
