;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16

[/Script/GameplayTags.GameplayTagsList]
+GameplayTagList=(Tag="Foley.Event.Handplant",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.Jump",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.Land",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.Run",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.RunBackwds",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.RunStrafe",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.Scuff",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.ScuffPivot",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.ScuffWall",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.Slide.Loop",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.Tumble",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.Walk",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="Foley.Event.WalkBackwds",DevComment="Footstep and movement foley event")
+GameplayTagList=(Tag="GPTags.GPAbilities.Skill_E",DevComment="Gameplay ability input tag")
+GameplayTagList=(Tag="GPTags.GPAbilities.Skill_Q",DevComment="Gameplay ability input tag")
