#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

// 프로젝트 전반에서 재사용할 네이티브 게임플레이 태그 모음
namespace GPTags
{
	// [0] Game : 시련 진행 상태 및 흐름 제어
	namespace Game
	{
		namespace Stage
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat);			// 전투 진행 중
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cleared);		// 시련 클리어됨
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reward);			// 보상 선택 중
		}
	}
	
	// [1] Ability : 어빌리티 실행 및 식별용 태그 (기존 유지)
	namespace Ability
	{
		namespace System
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateOnGiven); // 패시브용
		}
		namespace Action
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Targeting); // 록온
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interact);  // 상호작용
		}
		namespace Movement
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);	// 달리기
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dash);		// 대시
		}
		namespace Skill
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillRoot); // 부모 태그용
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Selection); // 스킬 선택/조준 상태 어빌리티
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary); // 평타
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot01);  // 스킬 1
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot02);  // 스킬 2
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ultimate); // 궁극기
			namespace Id
			{
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WaterPuddle);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NetTestProjectile);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SplitShot);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroundBurst);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThrownBurst);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PulseBurst);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LineShock);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MineBurst);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConeSlash);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagmaShot);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GelmirFury);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DarkSoloProjectile);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DarkStone);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DarkMist);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightningStrike);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IceMist);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalTorrent);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShatteringCrystal);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BigHammer);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BigSword);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicBigBubbles);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicBubbles);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Potion);
			}
			namespace Visual
			{
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Impact);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cast);
			}
		}
		namespace Enemy
		{
			// 공격 계열
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Melee);   // 근접 공격
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Ranged);  // 원거리 공격
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_AoE);     // 광역 공격
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_BossHeavy); // 보스 강공격
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_BossArea);  // 보스 광역 공격
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_BossSweep); // 보스 전방 휩쓸기 공격
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_BossGroundHands); // Sans rising ground-hands pattern
            
			// 유틸리티 및 특수 계열
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility_Dash);   // 이동기 돌진기 등
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility_Summon); // 쫄몹 소환
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility_Buff);   // 자버프
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility_BossSummon);     // 보스 소환 패턴
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility_BossPhaseShift); // 보스 페이즈 전환 패턴
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility_MatadorBullPattern); // Matador bull decoy charge pattern
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility_MatadorGroggy);      // Matador groggy/recover state ability
            
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death);          // 뒤져요
		}
		namespace Boss
		{
			namespace Matador
			{
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RapierThrust);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CapeGust);
			}
			namespace CrystalSeraph
			{
				// Native ability tags keep Crystal Seraph pattern activation in the shared GAS/BT path.
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Basic);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Laser);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prism);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Area);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Groggy);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Teleport);
			}
			namespace DarkKnight
			{
				// Dedicated tags keep Dark Armor Knight selection inside the shared GAS boss executor.
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Basic);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heavy);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sweep);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Guard);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Parry);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Counter);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Charge);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DarkWave);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroundCrack);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Groggy);
			}
		}
	}
	
	// [2] Damage : 데미지 타입 및 원소 속성 (RPG 필수)
	namespace Damage
	{
		namespace Type
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Physical);		// 물리 피해
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Magical);		// 마법 피해
		}
		namespace Element
		{													// 속성			영어	모델링 수
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pyros);			// 화염 속성		Pyros	1
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hydro);			// 물 속성		Hydro	1/2
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Volt);			// 전격 속성		Volt	0
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aero);			// 바람 속성		Aero	1
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lux);			// 빛 속성		Lux		0
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chaos);			// 혼돈 속성		Chaos	0
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Brute);			// 물리 속성		Brute	0
		}
		namespace Coef
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Atk);			// 공격력 계수
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Def);			// 대상 방어력 계수
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hp);				// 대상 최대 체력 계수
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(M_Atk);			// 마법력 계수
		}
		namespace Data
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Base);			// 물리/공통 기본 데미지
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseSpell);		// 마법 기본 데미지
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ToughnessBase);	// 강인도 기본 데미지
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Multiplier);
		}
	}

	// [3] State : 캐릭터 상태, 버프, 디버프
	namespace State
	{
		namespace Status
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fixed);			// 이동/회전 불가
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unstoppable);	// 저지불가 피격무시 데미지는 받음
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invincible);		// 데미지 무적
			namespace Enemy
			{
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aggroed);    // 어그로
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enraged);    // 광폭화
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MatadorGuarded); // Matador guarded damage reduction state
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MatadorMeleeActive); // Matador melee special is active
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalGuarded); // Crystal Seraph guarded damage reduction state
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WingCoreExposed); // Crystal Seraph partial vulnerability window
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Groggy);         // Groggy removes guarded damage reduction
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DarkGuarded);    // Dark Armor Knight directional guard
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ParryWindow);    // Dark Armor Knight active parry window
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GuardBroken);    // Dark Armor Knight guard depleted
			}
		}
		namespace Movement
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);		// 달리기
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dash);		// 회피 대쉬
		}
		namespace Skill
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Selecting);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Previewing);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ray);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TargetActor);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroundPosition);
		}
		namespace Buff
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shield);			// 보호막
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Haste);			// 가속 (이속/공속 증가)
		}
		namespace Debuff
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Burn);			// 화상 (도트 뎀)
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);			// 기절
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slow);			// 둔화
		}
	}

	// [4] Item : 유물 및 착용 장비 식별
	namespace Item
	{
		namespace Relic
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BloodthirsterTest);		// 테스트용 피바라기
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WarmogArmorTest);			// 테스트용 워모그
		}
		namespace Weapon
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeleeTest);		// 검 착용 중
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RangeTest);		// 활 착용 중
		}
	}

	// [5] Tech : run-level player tech choices
	namespace Tech
	{
		namespace Element
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pyros);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hydro);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Volt);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aero);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lux);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chaos);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Brute);
		}
	}

	// GameplayCue tags keep the engine-required "GameplayCue." root while staying in native project tag declarations.
	namespace GameplayCue
	{
		namespace Ability
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Trail_Magic);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Burst_Magic);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cast_Magic);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Active_Magic);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Impact_Magic);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Telegraph_Magic);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reflect_Magic);
		}
	}

	// [6] Event : 일회성 이벤트 트리거
	namespace Event
	{
		namespace Player
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);	// Player 피격 프레임
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackHit);	// Player 공격 타격 프레임
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActionEnd);	// Player 액션 종료 프레임
			
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ComboEnable);// Player 콤보 액션
		}
		namespace Skill
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConfirmPrimary);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConfirmSecondary);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cancel);
		}
		
		namespace Enemy
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);	// Enemy 피격 프레임
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackHit);	// Enemy 공격 타격 프레임
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActionEnd);	// Enemy 액션 종료 프레임
		}
	}

	// [7] Cooldown : 쿨다운
	namespace Cooldown
	{
		namespace Enemy
		{
			namespace Matador
			{
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RapierThrust);
				PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CapeGust);
			}
		}
		namespace Skill
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WaterPuddle);
			
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NetTestProjectile);

			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SplitShot);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagmaShot);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DarkSoloProjectile);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalTorrent);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DarkStone);

			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroundBurst);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightningStrike);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IceMist);
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BigHammer);

			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThrownBurst);

			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PulseBurst);

			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LineShock);

			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MineBurst);

			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConeSlash);

			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DashSlash);

			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifeDrainTarget);
		}
		namespace Data
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Duration);
		}
	}
	
	// [8] AI : BT 연동 논리상태 사용할수도 있을것 같아서 추가
	namespace AI
	{
		namespace State
		{
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);      // 대기 중
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Patrol);    // 정찰 중
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chasing);   // 추격 중
			PROJECT_EDEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat);    // 교전 중
		}
	}
}
